FROM python:3.12-slim

# Instala dependencias del sistema y el CLI de Google Cloud
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    gnupg \
    curl

# Agrega la clave del repositorio de Google Cloud
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg

# Agrega el repositorio de Google Cloud SDK
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
    | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

# Instala herramientas útiles y una versión específica del SDK de GCP
RUN apt-get update && apt-get install -y \
    git \
    vim \
    net-tools \
    build-essential \
    google-cloud-cli=473.0.0-0

# Define el directorio de trabajo
WORKDIR /ws/code

# Define PYTHONPATH para importar desde src
ENV PYTHONPATH=/ws/code/src
